# Uncomment the next line to define a global platform for your project
# platform :ios, '10.2'

target 'navigation' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for navigation
  pod 'Firebase'
  pod 'Alamofire'
  pod 'SwiftyJSON'
end
